[project]
name = "smart-contracts"
description = "Genesis Platform Contracts"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

[contracts.genesis-core-v2]
path = "contracts/genesis-core-v2.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
