[project]
name = "smart-contracts"
description = "Genesis Platform V4"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

# Deploy V4 Contracts
[contracts.genesis-missions-v4]
path = "contracts/genesis-missions-v4.clar"
clarity_version = 2
epoch = 2.5

[contracts.genesis-badges-v4]
path = "contracts/genesis-badges-v4.clar"
clarity_version = 2
epoch = 2.5

[contracts.genesis-core-v4]
path = "contracts/genesis-core-v4.clar"
clarity_version = 2
epoch = 2.5
